image:
  repository: apache/hive
  tag: 3.1.3

hivemetastore:
  configMap: hive-metastore-conf
  resources:
    requests:
      memory: 1Gi
      cpu: 500m
    limits:
      memory: 2Gi
      cpu: 1000m

postgresql:
  enabled: true
  postgresqlUsername: hive
  postgresqlPassword: hive
  postgresqlDatabase: metastore

extraEnvVars:
  - name: AWS_ACCESS_KEY_ID
    value: minio
  - name: AWS_SECRET_ACCESS_KEY
    value: minio123
  - name: S3_ENDPOINT
    value: http://minio:9000
  - name: AWS_REGION
    value: us-east-1
  - name: HADOOP_HOME
    value: /opt/hadoop
  - name: HADOOP_CLASSPATH
    value: /opt/hadoop/share/hadoop/tools/lib/* 