server:
  workers: 2
  coordinatorExtraConfig:
    query.max-memory: 4GB
    query.max-memory-per-node: 1GB
    query.max-total-memory-per-node: 2GB
  workerExtraConfig:
    query.max-memory-per-node: 1GB
    query.max-total-memory-per-node: 2GB
  resources:
    requests:
      cpu: 1
      memory: 2Gi
    limits:
      cpu: 2
      memory: 4Gi

additionalCatalogs:
  iceberg: |
    connector.name=iceberg
    hive.metastore.uri=thrift://hive-metastore:9083
    iceberg.file-format=PARQUET
    iceberg.catalog.type=HIVE_METASTORE
    hive.s3.aws-access-key=minio
    hive.s3.aws-secret-key=minio123
    hive.s3.endpoint=http://minio:9000
    hive.s3.path-style-access=true
    hive.s3.ssl.enabled=false

authentication:
  type: PASSWORD

additionalConfigProperties:
  - access-control.restricted-catalog-roles.catalogs=jmx->admin
  - http-server.authentication.allow-insecure-over-http=true 