createUserJob:
  useHelmHooks: false

airflow:
  image:
    repository: apache/airflow
    tag: 2.5.1
  executor: CeleryExecutor
  fernetKey: "your-fernet-key"  # Genera con: python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
  config:
    AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "True"
  users:
    - username: admin
      password: admin
      role: Admin
      email: admin@example.com
      firstname: Admin
      lastname: User

postgresql:
  enabled: true
  postgresqlUsername: airflow
  postgresqlPassword: airflow
  postgresqlDatabase: airflow

redis:
  enabled: true

web:
  service:
    type: ClusterIP
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi

dags:
  persistence:
    enabled: true
    size: 1Gi
  gitSync:
    enabled: false

workers:
  replicas: 2
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1000m
      memory: 2Gi 