apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: sales-data
  namespace: data-pipeline
  labels:
    strimzi.io/cluster: data-cluster
spec:
  partitions: 3
  replicas: 3
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824 