elasticsearchHosts: "http://elasticsearch-master:9200"

resources:
  requests:
    cpu: "200m"
    memory: "512Mi"
  limits:
    cpu: "500m"
    memory: "1Gi"

service:
  type: ClusterIP

ingress:
  enabled: false 